version: "3.9"

networks:
  tsa:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot-tmp:/var/certtmp
      - ./certbot-crt:/etc/letsencrypt
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - tsa
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot-crt:/etc/letsencrypt
      - ./certbot-tmp:/var/certtmp
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  backend:
    build:
      context: ./Back
    expose:
      - "8080"  # Expose для internal network
    networks:
      - tsa

  frontend:
    build:
      context: ./Web
    expose:
      - "5000"  # Expose для internal network
    environment:
      - NEXT_PUBLIC_API_URL=https://tsebulenko-agency.ru/api  # HTTPS теперь!
    networks:
      - tsa
      
volumes:
  certbot-crt:
  certbot-tmp:
